bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_O0 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_O2 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_O3 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_Os 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_Of 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_m32_O0 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_m32_O2 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_m32_O3 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_m32_Os 
bash run_utils_ehframe.sh -i /data/testsuite/utils/binutils/gcc_m32_Of
